### ISSUE TITLE
Use React v16

### ISSUE THREAD

**Issue by hieuhlc** [insin/react-maskedinput#114]
React v16 is released recently and it would be great if react-maskedinput uses latest version of React.

**Comment by qnodesign** [comment]
+1

**Comment by Thorarin** [comment]
I've made a pull request #115 to at least update the peerDependencies.

**Comment by leo-courbassier** [comment]
Please make it available to npm repo. The latest version 4.0.0 on npm repo still doesn't support React v16.

**Comment by didi0613** [comment]
Any updates on npm?
I still get the `requires a peer of react@^0.14.9 || ^15.3.0 but noneis installed. You must install peer dependencies yourself.` with latest version

**Comment by vcapretz** [comment]
+1 on this, I came here to open a PR updating the React version but I saw it is already there, it just need to be updated to npm, could you help us @insin?

**Comment by ajoshi0** [comment]
@iamdustan can you please help here

**Comment by insin** [comment]
Released v4.0.1
