### ISSUE TITLE
Release ETA?

### ISSUE THREAD

**Issue by Logiraptor** [insin/react-maskedinput#117]
There are a few commits on master ahead of the v4.0.0 release which seem to address some issues we're having. When will the next release be published?

**Comment by didi0613** [comment]
Any updates on this?
  @iamdustan @insin

**Comment by hozefaj** [comment]
@insin Any updates on this? The `peerDependencies` for reactv16 is something that is blocking us in our migration to v16.
  
 https://github.com/insin/react-maskedinput/issues/114 seems to have addressed the issue.

**Comment by vcapretz** [comment]
Is this project abandoned? I would like that it could still be maintained, maybe allowing other people to help you  @iamdustan @insin keeping this project up to date and releasing new npm versions!

**Comment by insin** [comment]
Released v4.0.1
