### ISSUE TITLE
please release a newer version

### ISSUE THREAD

**Issue by samlecuyer** [insin/react-maskedinput#14]
Most significantly, the `placeholderChar` is not supported in the 2.0 release, but support has since been added.  Can you publish a new version?

**Comment by MikaFima** [comment]
:+1:

**Comment by ghost** [comment]
:+1:

**Comment by dbrans** [comment]
:+1:

**Comment by dbrans** [comment]
In case anyone needs it, I've published latest (as of now) under dbrans-react-maskedinput:
`npm install --save dbrans-react-maskedinput`

**Comment by samlecuyer** [comment]
@insin bump

**Comment by oguzbilgic** [comment]
:+1: Also if possible update the react peer dependency or completely remove it like react-router. Currently it breaks the npm with react@v0.14.0-rc1. Component works with the newer versions of react though.
