### ISSUE TITLE
pass through pattern prop

### ISSUE THREAD

**Issue by yocontra** [insin/react-maskedinput#15]
Not sure what to do here.

Here's my use case:
- Credit card input
- Pattern is `'1111 1111 1111 1111'`
- Want keyboard that pops up to be a numeric keyboard, since the only editable characters are numbers

With a normal input you would pass a pattern of `[0-9]*` to the input and it will show a numeric keyboard on ios on android. Since react-maskedinput already uses this key, there is no way to do this.

Either need a way to pass this through, or better yet maybe maskedinput could pass the regex pattern through itself so the OS can show the correct keyboard

**Comment by insin** [comment]
Thoughts on renaming the current `pattern` prop to `mask` to avoid this?

Shadowing an existing HTML5 `<input>` prop seems like bad form, worth eating a major version bump for.

**Comment by yocontra** [comment]
@insin That seems like a good idea to me

**Comment by yocontra** [comment]
@insin Thanks!
