### ISSUE TITLE
Doesn't work in Google Chrome for Android

### ISSUE THREAD

**Issue by vguzev** [insin/react-maskedinput#19]
As far as I see this is because Android doesn't generate onKeyPress event for inputs...

**Comment by vguzev** [comment]
Generally speaking relying only on onKeyPress event is not right solution, because different input methods can be used. For example, hand-writing-tools or IME.

**Comment by flynfish** [comment]
:+1: we are also running into issues with IE on windows phone

**Comment by flynfish** [comment]
more info on Android issues we are seeing:

Android 5.1.1, Firefox 43. It only allows you to input the first 3 numbers. 

More info here:
https://github.com/sanniassin/react-input-mask/issues/11

**Comment by orkisz** [comment]
Is there any possibility this will be fixed?

**Comment by iamdustan** [comment]
PRs accepted.

**Comment by 9jaGuy** [comment]
The above fix didn't work for me....will do a PR with what worked for me

**Comment by nonmanifold** [comment]
the case duplicates likely duplicates #2 and my PR #33 should fix that by reporting to parent component, which should replace masked input with plain old input.

**Comment by axelson** [comment]
@9jaboy did you ever create a PR?

**Comment by 9jaGuy** [comment]
@axelson not yet....will do so in a bit.

**Comment by zomars** [comment]
I'm having the same issue here. Can I use a temporal fix?

**Comment by davidaubin** [comment]
nvm, this only work for chrome

**Comment by andersryanc** [comment]
I did some testing on BrowserStack for an app I'm working on right now and this latest fix / tag [v3.3.0-beta.1](https://github.com/insin/react-maskedinput/releases/tag/v3.3.0-beta.1) seems to be working in both Chrome and the Samsung "Internet" browsers on (on Galaxy S5, S6 and S7 at least)...

Is there any plan to push this out to NPM? I can't seem to install this easily unless I manually clone down this repo and run the build steps and then `cp` the files into `node_modules`...

**Comment by iamdustan** [comment]
@andersryanc did you test with that change in other browsers as well to ensure we didn’t regress anything?

**Comment by jimmyhmiller** [comment]
I'm getting different results on BrowserStack vs TestObject. On BrowserStack, the S7 works fine. On TestObject it doesn't.

Based on a user report, it isn't working for them on the S7 edge. Browserstack doesn't have one, but TestObject does, tried it and it does not work. If, however, I switch to the google keyboard, it works fine. It seems to be something about the way the samsung keyboard works.
