### ISSUE TITLE
Replace Gulp and JSHint with Babel/ESLint/Webpack

### ISSUE THREAD

**Issue by insin** [insin/react-maskedinput#20]
As per https://github.com/insin/react-router-form/commit/bc075ca54581789f0fd650e3372db60075bcaf9d

**Comment by bpugh** [comment]
I can submit a PR for this if you haven't already started on it.

**Comment by iamdustan** [comment]
@bpugh are you still interested in doing this?

**Comment by bpugh** [comment]
Sure! I was actually thinking of using https://github.com/insin/nwb which is what @insin is updating his repos with. Thoughts?

**Comment by iamdustan** [comment]
:thumbsup: sounds solid.

**Comment by iamdustan** [comment]
Closed by #31
