### ISSUE TITLE
main field in package.json is wrong

### ISSUE THREAD

**Issue by terebentina** [insin/react-maskedinput#24]
Currently trying to `npm i insin/react-maskedinput` (install straight from github since the npm package is out of date) results in a broken package in my node_modules: `main` in package.json points to `./lib/index.js` and the only folder available is `dist`.
You should point the main to dist/react-maskedinput.js

**Comment by jquense** [comment]
you need to run the build step to create the main file when installing directly from github. Setting the main file to dist folder would not be great.

**Comment by terebentina** [comment]
Hmm, this is less than ideal then...do you mind publishing the latest version to npm, please? I need the version for react 0.14.0

**Comment by jquense** [comment]
that's up to @insin :) in the meantime tho you can use: `intljusticemission/react-maskedinput` which is our fork, it has the lib file checked in, so no build step

**Comment by terebentina** [comment]
Doh, you answered so fast I thought you were the owner :) Thanks for the help
