### ISSUE TITLE
Make value property consistent with React

### ISSUE THREAD

**Issue by anthonator** [insin/react-maskedinput#25]
`value` should be changed to `defaultValue` to make this consistent with React inputs. Currently, `react-maskedinput`'s `value` property behaves identical to React's `defaultValue` input property.

`value` should also reflect any changes made. Similar to how React handles `value` on input components.

**Comment by berrtech** [comment]
+1, thought i was doing something wrong trying to make masked input controlled, appeared i wasn't

**Comment by brusenskiy** [comment]
Can't reset an input value by setting `value` property to null or an empty string.

**Comment by boris-ulyanov** [comment]
:+1: related to https://github.com/insin/react-maskedinput/issues/3

**Comment by diogobeda** [comment]
Any updates on this? Seems like the project is not mantained anymore.
@insin want some help?

**Comment by igorsantos07** [comment]
+1 on this. Sadly there's are a lot of mask packages that have the same issue, behaving different of what we expect...

@diogobeda, https://github.com/sanniassin/react-input-mask this one seems to do the trick.
