### ISSUE TITLE
Edit value programmatically

### ISSUE THREAD

**Issue by FranBran** [insin/react-maskedinput#3]
Is it possible to edit a value programmatically?

e.g. for a default input-field you just need to edit its value-attribute, but for a maskedinput, the value is only used as a default-value.

**Comment by ukko** [comment]
@DERIIIFranz add into MaskedInput class 

``` javascript
  componentWillReceiveProps:function(nextProps) {
    if (nextProps.value && nextProps.value !== this.mask.value) {
      this.mask.setValue(nextProps.value);
    }
  },
```

**Comment by FranBran** [comment]
great! Is this going to be adopted in the next release?

**Comment by insin** [comment]
Yes. Thanks @ukko
