### ISSUE TITLE
Browser Bundles links not working

### ISSUE THREAD

**Issue by hugooliveirad** [insin/react-maskedinput#35]
These links aren't working:
- https://npmcdn.com/react-maskedinput@3.1.0/umd/react-maskedinput.js
- https://npmcdn.com/react-maskedinput@3.1.0/umd/react-maskedinput.min.js

README.md point to them at the [Browser Bundle section](https://github.com/insin/react-maskedinput#browser-bundle)

**Comment by iamdustan** [comment]
Oops. @bpugh it seems like we need to keep the compiled build in the repo for that? Is that a requirement of npmcdn?

**Comment by iamdustan** [comment]
At first glance of npmcdn it looks like the dist should be published to npm. Can anyone verify that?

**Comment by bpugh** [comment]
According to npmcdn docs they can be published under umd or dist folder.

**Comment by jquense** [comment]
ya it wants a path to a browser dist build. its abit annoying to keep in the repo but probably worth it for this use case ?

**Comment by iamdustan** [comment]
Looking at the react-router repo itself, I didn’t see a dist/umd directory (unless I looked in the wrong place somehow). It seemed like it could just be published with that. I’d take publishing umd builds to npm over GH personally, but am open to popular opinion.

**Comment by bpugh** [comment]
Yeah the whole point of npmcdn is that you only need to publish the dist files to npm and it pulls them in automagically

**Comment by jquense** [comment]
oops yeah too early for me still. yeah we should only need to publish the dist files for npmcdn, no need to keep them in the repo

**Comment by iamdustan** [comment]
Preparing to publish 3.1.1 with dist in npm.

**Comment by bpugh** [comment]
Yeah sorry should thought about that we would need to publish a new version to npm once we made that change.

**Comment by iamdustan** [comment]
3.1.1 published. Closed by eff2ae6bcfb9a98d8e56984848b6e8219b9cc9dd
- https://npmcdn.com/react-maskedinput@3.1.1/umd/react-maskedinput.js
- https://npmcdn.com/react-maskedinput@3.1.1/umd/react-maskedinput.min.js

**Comment by iamdustan** [comment]
Thanks for reporting @hugobessaa

**Comment by hugooliveirad** [comment]
Thanks for fixing that :smile:!
