### ISSUE TITLE
Consider Making "Mask" Not Required

### ISSUE THREAD

**Issue by netpoetica** [insin/react-maskedinput#54]
In my use case, I have a very generic component where I want to have mask on maybe 20% of all components, but I do not want to have to if/then between MaskedInput and plain input. Why must "mask" be a required prop? Is this intentional?

**Comment by iamdustan** [comment]
We’re not going to do this. Even if you render a `MaskedInput` without a mask, users will still likely take the hit of the additional lifecycle logic in here and it creates a very odd API, IMO.

**Comment by netpoetica** [comment]
I understand this. It is likely that the best solution (implemented by end-user of this lib) is to create a simple BasicInput component that just wraps an HTML input element, this way you can do simple things and treat them the same. 

For example, in you want to get the value of an HTML input vs. a MaskedInput, you need to do something like:

```
    let fieldInput = this.refs.fieldInput;
    let fieldInputVal = fieldInput.value || findDOMNode(fieldInput).value;
```

but if you wrap a basic input as it's own component, you can treat it the same.

Cheers
