### ISSUE TITLE
Fails to work with a pattern with a starting static character

### ISSUE THREAD

**Issue by leoasis** [insin/react-maskedinput#7]
With a pattern like `(111) 111 - 1111`, the input does not accept any character when it's empty

**Comment by jordaaash** [comment]
+1 Ran into the exact same issue with phone numbers.

**Comment by jordaaash** [comment]
This is actually due to a problem in the upstream project, [inputmask-core](https://github.com/insin/inputmask-core). I'm submitting a PR now.
