### ISSUE TITLE
React.PropTypes warning

### ISSUE THREAD

**Issue by andersryanc** [insin/react-maskedinput#70]
I'm getting the following error in my console:

<img width="849" alt="screen shot 2016-08-31 at 2 30 30 pm" src="https://cloud.githubusercontent.com/assets/689046/18146985/905ec3a0-6f87-11e6-83fc-160445676040.png">

My current version of React is `^15.1.0`. Let me know if you need any more details.

**Comment by andersryanc** [comment]
Hmm... strangely, reading through your `src/index.js` I can't see where that would be coming from.

**Comment by TheTedAdams** [comment]
It's right here:

https://github.com/insin/react-maskedinput/blob/master/src/index.js#L62

PR #94 would fix it... but looks like the maintainer of this repo is MIA...

**Comment by MichaelDeBoey** [comment]
@insin I think we're all waiting for this one. 😕
Please merge #94! 🙂
