### ISSUE TITLE
Does not work in latest chrome on android

### ISSUE THREAD

**Issue by kibin** [insin/react-maskedinput#71]
I have nexus 5x with android 7.0 and latest chrome installed, nothing seems to work for me. On firefox everything is working fine

**Comment by iamdustan** [comment]
what version of react-maskedinput are you using?

**Comment by kibin** [comment]
Was using 3.2.3 before you asked. Updated to 3.3.0 and now problem is gone, thanks!

**Comment by iamdustan** [comment]
woohoo!
