### ISSUE TITLE
[Question] Support react-lite

### ISSUE THREAD

**Issue by alexeybondarenko** [insin/react-maskedinput#73]
I've tried to use `masked-input` with `react-lite`, but it not works because masked-input uses internal react modules. It'is possible to implement masked input without `lib/ReactInputSelection` access?

https://github.com/Lucifier129/react-lite/issues/81

**Comment by iamdustan** [comment]
Oi! This is using react-internals? :grimacing:

That definitely needs to be rectified...

**Comment by jquense** [comment]
i have a hand written version at: https://github.com/jquense/react-widgets/blob/master/src/util/caret.js i'm sure there are also like 1351356 other options on npm. so Yeha it should be easy enough to not rely on the internals

**Comment by alexeybondarenko** [comment]
#74 I've made PR
