### ISSUE TITLE
Pattern changes are not immediately reflected

### ISSUE THREAD

**Issue by muffinresearch** [insin/react-maskedinput#8]
For things like credit cards the pattern needs to be updated on the fly. E.g. if an amex card is detected that uses a different pattern to visa for example. 

Currently MaskedInput doesn't use setPattern to update the pattern when it changes so changing the pattern dynamically results in no changes.

**Comment by andrevvalle** [comment]
+1

**Comment by Philmod** [comment]
+1

**Comment by insin** [comment]
What should we do with the existing value when setting the pattern?

Default is currently to attempt to pass on the current raw value.

**Comment by muffinresearch** [comment]
@insin I've just gotten around to testing this out and it's looking pretty good!

_Fwiw all examples are using braintree's test card numbers_

My use case is updating a credit card pattern to different card format as the input is entered/pasted etc.

Starting with a visa pattern e.g. `1111 1111 1111 1111` entering this is fine: `4111 1111 1111 1111`

If I start over (with the pattern being visa by default) if I start typing '37' to get the amex detection on my card input to change the pattern I end up with the new pattern, but the caret is at the end. E.g. typing 37 gives me:  `37__ ______ _____`.

Starting over with an empty field if I paste in an amex number e.g. `371449635398431` then the pattern is correctly updated to `1111 111111 11111` which is excellent - and what I'd hoped `getRawValue()` would help with.

The only nit is the caret is at the start of the string, post pattern change.

When pasting back the longer visa example: `4111 1111 1111 1111`

The field ends up with this:

`4111 1111 1111 111_`

Again the caret is at the start of the inputted string. Ideally I could paste `4111 1111 1111 1111` and get `4111 1111 1111 1111` but I can see dealing with the pattern change around the paste will be tricky.

**Comment by andrevvalle** [comment]
@muffinresearch I created a component that will help you.
https://github.com/andrevvalle/react-mask

**Comment by muffinresearch** [comment]
@insin I've been looking at  PR #9 by @Philmod. With one small change it looks to address most of the issues I descibed above wrt selection above. 

The only case that still doesn't work is going from the shorter pattern to a longer one. Not losing part of the pasted string is going to be hard. But if the selection could be in the right place I think we're close enough to something releasable.

I'll add some comments to the PR.
