### ISSUE TITLE
Server side rendering failing on undefined navigator

### ISSUE THREAD

**Issue by justinrex** [insin/react-maskedinput#82]
https://github.com/insin/react-maskedinput/blob/master/src/index.js#L239

running a node server and trying to render this server side. Running into an issue because navigator is not available on the server

line 239
`return navigator.userAgent.match(/Android/i)`

**Comment by aesopwolf** [comment]
Just ran into the same issue. Seems like the events handlers can be stored in `this.state` after `componentDidMount`.

**Comment by aesopwolf** [comment]
It was actually a lot easier than that https://github.com/insin/react-maskedinput/pull/83

**Comment by justinrex** [comment]
👍
