### ISSUE TITLE
Move cursor to the first valuable place

### ISSUE THREAD

**Issue by sidoruk-sv** [insin/react-maskedinput#92]
When I have a mask, that begins with some masked symbol `()[]{}` etc. 
It will be good to move cursor to the place where first number will appear, not before `(`:
http://take.ms/SAwpD

**Comment by jerrygreen** [comment]
totally agree! this UX is so bad
it's weird to tap backspace tens of times to remove NOTHING, like... I'll try to describe, here's my input data and some comments:

> `+1 (123) 1`
> 
> whops, wrong last digit in parentheses, need to delete... BACKSPACE!
> 
> `+1 (123) `
> 
> yea, nice, go deeper! BACKSPACE!
> 
> `+1 (123)`
> 
> wait wuut?! did I tap? not sure... BACKSPACE!
> 
> `+1 (123)`
> 
> does it even work? I think it's bugged, shit... BACKSPACE!
> 
> `+1 (12 )`
> 
> HOLY MOLY, it's working, thank god... shitty website

So why these blank/ethereal characters counts as characters for backspace (which are just part of mask, not the data)?

**Comment by gotrecillo** [comment]
Please, really please.
